#转义字符
#{hp}: 宠物HP
#{maxHP}
#{lv}: 宠物等级
#{name}: 宠物类型|名称
#{sp}
#{maxSP}
#{exp}
#{maxExp}
#{spBar}: SP显示条
#{hpBar}: 血量显示
#{expBar}: 经验显示
#{owner}: 主人名称
#{n}: 换行
训练师最高等级: 100
货币单位: 币
训练师拥有宠物数量: 3,4,5,6,7,8,9,10,11,12
初始升级经验值: 10
等级经验倍率: 2
幸运值最大暴击加成: 0.1
宠物名称最大长度: 5
宠物头衔显示格式: Lv.{lv} {name} |❤.{hp}|{n}{spBar} {owner}
管理人员:
  - iGxnon
  - LyricCamera6544