#转义字符
#{hp}: 宠物HP
#{maxHP}
#{lv}: 宠物等级
#{name}: 宠物类型|名称
#{sp}: 宠物SP
#{maxSP}: 宠物最大SP
#{exp}: 宠物经验
#{maxExp}: 宠物升级所需经验
#{spBar}: SP显示条
#{hpBar}: 血量显示
#{expBar}: 经验显示
#{owner}: 主人名称
#{n}: 换行
训练师最高等级: 100
货币单位: 币
# 10% 20% 30%... 的最大等级对应的数量
训练师拥有宠物数量: 3,4,5,6,7,8,9,10,11,12
初始升级经验值: 10
等级经验倍率: 2
幸运值最大暴击加成: 0.1
宠物名称最大长度: 5
宠物头衔显示格式: Lv.{lv} {name} |❤.{hp}|{n}{spBar} {owner}
管理人员:
  - iGxnon
  - LyricCamera6544
#基础道具价格:
#  - "幸运草:1000"
#  - "小型HP剂:1000"
#  - "小型SP剂:1000"
#  - "中型HP剂:1000"
#  - "中型SP剂:1000"
#  - "大型HP剂:1000"
#  - "大型SP剂:1000"
#  - "HP扩容:1000"
#  - "SP扩容:1000"
#  - "复活石:1000"